general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 10 min: dim screen + keyboard backlight off
listener {
    timeout = 600
    on-timeout = brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

listener {
    timeout = 600
    on-timeout = brightnessctl -sd *::kbd_backlight set 0
    on-resume = brightnessctl -rd *::kbd_backlight
}

# 20 min: lock screen
listener {
    timeout = 1200
    on-timeout = loginctl lock-session
}

# 20 min: screen off
listener {
    timeout = 1200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
